// Generated by CoffeeScript 1.9.3
(function() {
  var SUrl;

  SUrl = (function() {
    var ALPHABET, BASE, ShortUrl, models;

    BASE = 62;

    ALPHABET = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

    models = require('../models/index');

    ShortUrl = models.ShortUrl;

    function SUrl() {}

    SUrl.prototype.create = function(str) {
      models.ShortUrl.findOrCreate({
        where: {
          Url: str
        }
      }).spread(function(shorturl, created) {
        console.log(shorturl.get({
          plain: true
        }));
        return console.log(created);
      });
      return "a";
    };

    SUrl.prototype.decode = function(str) {
      var darr;
      darr = str.split('');
      darr[0] = ALPHABET.indexOf(darr[0]);
      return darr.reduce(function(id, current) {
        return (id * BASE) + ALPHABET.indexOf(current);
      });
    };

    SUrl.prototype.encode = function(id) {
      var encoded;
      console.log(id);
      encoded = '';
      while (id > 0) {
        console.log(id);
        encoded += ALPHABET[id % BASE];
        id = parseInt(id / BASE);
      }
      console.log('Return: ' + encoded);
      return encoded;
    };

    return SUrl;

  })();

  module.exports = SUrl;

}).call(this);

//# sourceMappingURL=surl.js.map
