// Generated by CoffeeScript 1.9.3
(function() {
  var SUrl;

  SUrl = (function() {
    var ALPHABET, BASE;

    BASE = 62;

    ALPHABET = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';

    function SUrl() {}

    SUrl.prototype.decode = function(str) {
      var decodearray, result;
      console.log("decoding: " + str);
      console.log(str.split(''));
      decodearray = str.split('');
      decodearray[0] = ALPHABET.indexOf(decodearray[0]);
      result = decodearray.reduce(function(id, current) {
        var val;
        console.log('id: ' + id + ' , current: ' + current);
        console.log(ALPHABET.indexOf(current));
        console.log(2 * BASE);
        val = (id * BASE) + ALPHABET.indexOf(current);
        console.log(val);
        return val;
      });
      console.log(result);
      return 23;
    };

    return SUrl;

  })();

  module.exports = SUrl;

}).call(this);

//# sourceMappingURL=surl.js.map
